### PR TITLE
Add retries to requests to server

### PR DESCRIPTION
**Pull request by romasku**
Related to https://github.com/neuro-inc/neuro-flow/issues/411

### CODE REVIEW

**Comment by romasku** [comment]
We can make all requests to our server retriable by making all of them idempotent (we can generate ids on the client, and update/delete is already idempotent).
Do you think it worth it?

**Comment by asvetlov** [comment]
> We can make all requests to our server retriable by making all of them idempotent (we can generate ids on the client, and update/delete is already idempotent).
> Do you think it worth it?

I thought about it. Sounds like a good future improvement. Should wait for storage implementation cleanup anyway I

**Comment by asvetlov** [comment]
Sorry, close by accidental click. Please resolve the conflict.

**Review by asvetlov — APPROVED** [review]
lgtm

**Pull request merged**
