### PR TITLE
Support preset parametrization for image build job with "build_preset" option

### LINKED ISSUE #197: Add `--preset` to image declaration and pass it to `neuro-extras image build`

### PR DESCRIPTION
**Pull request by YevheniiSemendiak**
Closes #197 

Note: in 671bc3a I've removed the logic of preset inheriting from the "defaults" section since It probably would be more uncomfortable than comfortable to use. My first thought when I added it was "the support of unified behavior".
We could naturally return in back if someone thinks it would be better to have it.

### CODE REVIEW

**Review by asvetlov — COMMENTED** [review]
Run `make docs` please

**Comment by asvetlov** [comment]
fix conflicts please

**Comment by YevheniiSemendiak** [comment]
@asvetlov, I've resolved the conflicts and we could proceed with the review and merge 🙂

**Review by asvetlov — APPROVED** [review]
LGTM

**Pull request merged**
